import 'package:flutter/material.dart';

import 'api/platform_client.dart';
import 'auth/identity.dart';
import 'design/primitives.dart';
import 'design/tokens.dart';

/// Navigation and layout.
///
/// Two destinations rather than a guess at the client's information
/// architecture. What this application is *for* is the first thing that gets
/// designed properly, and a bootstrap that shipped eight speculative screens
/// would be eight screens somebody had to delete.
class AppShell extends StatefulWidget {
  const AppShell({super.key});

  @override
  State<AppShell> createState() => _AppShellState();
}

class _AppShellState extends State<AppShell> {
  int _destination = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: <Widget>[
          NavigationRail(
            selectedIndex: _destination,
            onDestinationSelected: (int index) =>
                setState(() => _destination = index),
            labelType: NavigationRailLabelType.all,
            destinations: const <NavigationRailDestination>[
              NavigationRailDestination(
                icon: Icon(Icons.people_outline),
                selectedIcon: Icon(Icons.people),
                label: Text('Records'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.settings_outlined),
                selectedIcon: Icon(Icons.settings),
                label: Text('Settings'),
              ),
            ],
          ),
          const VerticalDivider(width: 1),
          Expanded(
            child: _destination == 0
                ? const _RecordsPage()
                : const _SettingsPage(),
          ),
        ],
      ),
    );
  }
}

/// Where the client's own records will go.
///
/// Deliberately empty. Nothing generated by Baker contains invented customers,
/// orders or metrics: an application demonstrated with fake data in it is one
/// somebody eventually demonstrates by accident, and the empty state is the
/// honest description of a codebase on its first day.
class _RecordsPage extends StatelessWidget {
  const _RecordsPage();

  @override
  Widget build(BuildContext context) {
    return AppPage(
      title: 'Records',
      child: AppPanel(
        title: 'Nothing here yet',
        child: Text(
          'This screen is where the records this application is for will go. '
          'It is empty because nothing has been connected to it — not because '
          'the connection failed.',
          style: Theme.of(context).textTheme.bodyMedium,
        ),
      ),
    );
  }
}

class _SettingsPage extends StatelessWidget {
  const _SettingsPage();

  @override
  Widget build(BuildContext context) {
    final PlatformClient client = PlatformClient.fromEnvironment();
    final Identity identity = Identity.current();
    return AppPage(
      title: 'Settings',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          AppPanel(
            title: 'Platform',
            // Said rather than assumed. A build with no address configured
            // looks exactly like one whose address is unreachable until
            // somebody says which it is.
            child: AppDetail(
              label: 'API address',
              value: client.isConfigured
                  ? client.baseUri.toString()
                  : 'Not set. Pass --dart-define=CITADEL_PLATFORM_API_BASE_URL.',
            ),
          ),
          const SizedBox(height: AppTokens.space3),
          AppPanel(
            title: 'Signed in as',
            child: AppDetail(
              label: 'Identity',
              value: identity.describe(),
            ),
          ),
        ],
      ),
    );
  }
}
